services:
  gateway-redis:
    image: redis:alpine
    hostname: gw_redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "6379:6379"
    networks:
      - outer
      - external-b
      
  gateway-api:
    build:
      context: api-gateway/
      dockerfile: Dockerfile
    hostname: gw_api
    env_file: api-gateway.env
    depends_on:
      gateway-redis:
        condition: service_healthy
    networks:
      - outer
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "2181:2181"
    networks:
      - inner
      - external-b
    
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    restart: always
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "9092:9092"
    networks:
      - inner
      - external-b

  kafka-ui:
    build:
      context: conf/base/kafka_ui
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    healthcheck: 
      test: curl -s http://localhost:8080 > /dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - inner
      - external-b

networks:
  outer:
    driver: bridge
    internal: true

  inner:
    driver: bridge
    internal: true

  external-b:
    driver: bridge
    internal: false