apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
  
  - name: Elastic
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    editable: true