{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Monitoring jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"prometheus\"}) or vector(inf)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CADvisor state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"cadvisor\"}) or vector(inf)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node-exporter state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"nodeexporter\"}) or vector(inf)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx-exporter state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"nginx\"}) or vector(inf)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}