{
 "title": "Memory Usage",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Services",
    "query": {
     "query": "label_values(container_last_seen,container_label_com_docker_compose_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory left on host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{}/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Aggregated memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "All containers memory usage ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_scope!=\"\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Base scope memory usage ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_scope=\"base\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MONALOG scope memory usage ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_scope=\"monalog\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Databases memory usage ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_db_container=\"yes\"})/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container  memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "${Services} memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "repeat": "Services",
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_com_docker_compose_service=~\"${Services}\"}/1024/1024) or vector(inf)",
     "legendFormat": "All memory"
    },
    {
     "expr": "max(container_memory_rss {container_label_com_docker_compose_service=~\"${Services}\"}/1024/1024) or vector(inf)",
     "legendFormat": "App only memory"
    }
   ]
  }
 ]
}